Fix Flake Inputs

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -35,7 +35,9 @@ jobs:
 
       - name: Block if There's a Release
         if: ${{ steps.check-tag.outputs.exists != 'false' }}
-        run: echo "::error file=Cargo.toml,title=Refusing to Release::Tag ${{ steps.check-tag.outputs.tag }} already exists" && exit 1
+        run:
+          echo "::error file=Cargo.toml,title=Refusing to Release::Tag ${{
+          steps.check-tag.outputs.tag }} already exists" && exit 1
 
       - name: Build
         run: |
@@ -44,7 +46,7 @@ jobs:
       - name: Generate artifact attestation
         uses: actions/attest-build-provenance@v2
         with:
-          subject-path: 'target/release/gh-grader-preview'
+          subject-path: "target/release/gh-grader-preview"
 
       - name: Upload Binary Artifact
         uses: actions/upload-artifact@v4
